In [1]:
import numpy as np

In [2]:
def create_board():
    board = np .zeros((6,7))
    return board 

In [3]:
board = create_board()
print(board)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
board = create_board() #testchange22
game_over = False
turn = 0
while not game_over:
    # Ask for player 1 input
    if turn ==0:
        selection = int(input("player 1 Make your selection(0-6):"))

    #Ask for player 2 input
    else:
        selection = int(input("player 1 Make your selection(0-6):"))
    turn +=1
    turn = turn % 2


player 1 Make your selection(0-6):2
player 1 Make your selection(0-6):4
player 1 Make your selection(0-6):2
